#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Making the images the cases run over, in a working directory.

They are generated by `revenant-imagegen` and never committed: a 128 MiB image
in a repository would be a 128 MiB image in every clone for ever, and one built
by the tool under test is reproducible from the tool under test.

A fixture already in the working directory is reused. They are deterministic by
construction, so rebuilding one would produce the same bytes and cost the time
again.
"""
from __future__ import annotations

import subprocess
from pathlib import Path

import cases
import measure


def _generate(generator: Path, fixture: cases.Fixture, path: Path) -> None:
    argv = [str(generator), fixture.verb, str(path), *fixture.args]
    result = subprocess.run(argv, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        raise measure.CaseFailed(f"generating {path.name} failed:\n{result.stderr}")


def ensure(generator: Path, fixture: cases.Fixture, work_dir: Path) -> Path:
    """The fixture's path, generating it if the working directory lacks it."""
    path = work_dir / fixture.filename
    if not path.is_file():
        _generate(generator, fixture, path)
    return path
